export const translations = {
  ru: {
    login: "Вход",
    register: "Регистрация",
    email: "Email",
    password: "Пароль",
    repeatPassword: "Повторите пароль",
    loginBtn: "Войти",
    registerBtn: "Создать аккаунт",
    slogan: "Помогаем ученикам по-настоящему понимать!",
    whoAreYou: "Кто вы?",
    roleElementary: "Ученик начальных классов",
    roleMiddle: "Ученик средней школы",
    roleStudent: "Студент",
    roleAdult: "Взрослый / Для себя",
    next: "Далее",
    yourProfile: "Ваш профиль",
    name: "Имя",
    surname: "Фамилия",
    nickname: "Никнейм",
    finish: "Завершить",
    chooseAvatar: "Выберите аватар",
    gallery: "Галерея",
    cancel: "Отмена",
    change: "Изменить",
    hello: "Привет",
    progress: "Прогресс",
    continueLesson: "Продолжить обучение",
    streakDays: "дней подряд",
    topicsCompleted: "тем завершено",
    recentlyViewed: "Недавно просмотренные:",
    seeAll: "Посмотреть всё",
    dictionaryWip: "(Словарь в разработке)",
    chatbot: "Чат-бот",
    chatbotWip: "(Чат-бот в разработке)",
    lectures: "Лекции",
    editProfile: "Редактировать профиль",
    achievements: "Достижения",
    settings: "Настройки",
    logout: "Выйти",
    dictionary: "Словарь",
    editProfile: "Изменить профиль",
    achievements: "Достижения",
    settings: "Настройки",
    logOut: "Выйти с акаунта",
    editProfilePicture: "Изменить фотографию профиля",
    chooseProgramTitle: "Программа обучения",
    chooseProgramDesc:
      "Выберите школьную программу, по которой хотите учиться.",
    selectProgramBtn: "Выбрать программу",
    searchCountry: "Поиск страны...",
  },
  en: {
    login: "Log in",
    register: "Sign up",
    email: "Email",
    password: "Password",
    repeatPassword: "Repeat password",
    loginBtn: "Log in",
    registerBtn: "Create account",
    slogan: "Helping students truly understand!",
    whoAreYou: "Who are you?",
    roleElementary: "Elementary school student",
    roleMiddle: "Middle school student",
    roleStudent: "Student",
    roleAdult: "Adult / For myself",
    next: "Next",
    yourProfile: "Your profile",
    name: "First name",
    surname: "Last name",
    nickname: "Nickname",
    finish: "Finish",
    chooseAvatar: "Choose avatar",
    gallery: "Gallery",
    cancel: "Cancel",
    change: "Change",
    hello: "Hello",
    progress: "Progress",
    continueLesson: "Continue learning",
    streakDays: "day streak",
    topicsCompleted: "topics completed",
    recentlyViewed: "Recently viewed:",
    seeAll: "See all",
    dictionaryWip: "(Dictionary coming soon)",
    chatbot: "ChatBot",
    chatbotWip: "(ChatBot coming soon)",
    lectures: "Lectures",
    editProfile: "Edit profile",
    achievements: "Achievements",
    settings: "Settings",
    logout: "Log out",
    dictionary: "Dictionary",
    editProfile: "Edit profile",
    achievements: "Achievements",
    settings: "Settings",
    logOut: "Log out",
    editProfilePicture: "Edit profile picture",
    chooseProgramTitle: "Curriculum",
    chooseProgramDesc: "Choose the school program you want to follow.",
    selectProgramBtn: "Choose program",
    searchCountry: "Search country...",
  },
};

export function detectLanguage() {
  const browserLang = navigator.language.slice(0, 2); // "en-US" -> "en"
  return browserLang === "ru" ? "ru" : browserLang === "en" ? "en" : "ru";
}
