export const translations = {
  ru: {
    login: "Вход",
    register: "Регистрация",
    email: "Email",
    password: "Пароль",
    repeatPassword: "Повторите пароль",
    loginBtn: "Войти",
    registerBtn: "Создать аккаунт",
    slogan: "Помогаем ученикам по-настоящему понимать!",
    whoAreYou: "Кто вы?",
    roleElementary: "Ученик начальных классов",
    roleMiddle: "Ученик средней школы",
    roleStudent: "Студент",
    roleAdult: "Взрослый / Для себя",
    next: "Далее",
    yourProfile: "Ваш профиль",
    name: "Имя",
    surname: "Фамилия",
    nickname: "Никнейм",
    finish: "Завершить",
    chooseAvatar: "Выберите аватар",
    gallery: "Галерея",
    cancel: "Отмена",
    change: "Изменить",
    hello: "Привет",
  },
  en: {
    login: "Log in",
    register: "Sign up",
    email: "Email",
    password: "Password",
    repeatPassword: "Repeat password",
    loginBtn: "Log in",
    registerBtn: "Create account",
    slogan: "Helping students truly understand!",
    whoAreYou: "Who are you?",
    roleElementary: "Elementary school student",
    roleMiddle: "Middle school student",
    roleStudent: "Student",
    roleAdult: "Adult / For myself",
    next: "Next",
    yourProfile: "Your profile",
    name: "First name",
    surname: "Last name",
    nickname: "Nickname",
    finish: "Finish",
    chooseAvatar: "Choose avatar",
    gallery: "Gallery",
    cancel: "Cancel",
    change: "Change",
    hello: "Hello",
  },
};

export function detectLanguage() {
  const browserLang = navigator.language.slice(0, 2); // "en-US" -> "en"
  return browserLang === "ru" ? "ru" : browserLang === "en" ? "en" : "ru";
}
